### ISSUE TITLE
Wrong result cached from time to time, must restart proxy

### ISSUE THREAD

**Issue by jarthod** [chrisDeFouRire/tlsproxy#2]
After using `tlsproxy` for just a few hours I noticed an annoying issue, it sometimes fails to issue a cert and returns an SSL error of the like:
```
curl -v https://status.geojs.io
* Rebuilt URL to: https://status.geojs.io/
*   Trying 2604:a880:cad:d0::6476:3001...
* TCP_NODELAY set
* Connected to status.geojs.io (2604:a880:cad:d0::6476:3001) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
And it does this quickly (as if it wasn't even trying to validate) and the result stay cached and always return this until I restart the proxy. Then I can retry and the cert is issued properly. for 10 certs issued, I had to do 2 restarts. I don't know what the error was as nothing is logged but this definitely looks like an issue ;) if there's an error it should say so and depending on the error it should not cache the result and retry instead.

**Comment by chrisDeFouRire** [comment]
I must add a façade to a number of functions to bettershow errors, the libraries I'm using tend to hide errors silently. I'm suspecting rate limiting, but only proper debug information could prove/disprove it

**Comment by jarthod** [comment]
Well after checking the code I see the most important part (`getCertificate`) does return an error, and you already display it but only in debug mode. So I'll start by enabling debug mode on my server to see how it looks but I don't think this kind of error belongs to debug mode ;)

**Comment by jarthod** [comment]
Ah I didn't saw it was a new commit ;) thanks for that! I need to wait the release to try then.

**Comment by chrisDeFouRire** [comment]
That's code I've pushed 2 minutes ago, I'm pushing a new release (2.3)

**Comment by chrisDeFouRire** [comment]
Release 2.3 with `-debug` option should make the problem clearer... It's published now

**Comment by chrisDeFouRire** [comment]
As for debug mode, it was a way to test this code path without disrupting users...
I'll definitely the add error reporting to the "non debug" mode if it does catch interesting errors.

**Comment by jarthod** [comment]
Great, thanks! will try that ;)

**Comment by jarthod** [comment]
Ok I managed to reproduce the issue with another domain and  the debug enabled.
This is the URL: https://status.yourtaximeter.com/
I haven't restarted the proxy yet so the problem is still here.

Here is the debug output when we try to access this host:
```
tlsproxy: 2017/09/24 09:54:47 Getting cert for status.yourtaximeter.com
tlsproxy: 2017/09/24 09:54:47 GetCertificate debug: acme/autocert: missing certificate
```
It's the same error since the first query to his domain.
I'm not sure what this "[missing certificate](https://github.com/golang/crypto/blob/master/acme/autocert/autocert.go#L690)" means, but it's not even trying to get it as the response is very fast.
There's no cert with this name in the `cert` folder.

To me it looks like it failed the first time and cached an invalid result or something like that.
I'm pretty sure if I restart the proxy it'll work fine as it did the other times.
Is there anything more I can do to help?

**Comment by jarthod** [comment]
I just got more info with another failing cert (https://status.myownconference.ru), here is what I have in the log now:
```
tlsproxy: 2017/09/28 16:31:59 DEBUG: get status.myownconference.ru
tlsproxy: 2017/09/28 16:31:59 Cache Get debug: acme/autocert: certificate cache miss
tlsproxy: 2017/09/28 16:31:59 Getting cert for status.myownconference.ru
tlsproxy: 2017/09/28 16:31:59 GetCertificate debug: 400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce zvBhhB5kyR2Mxr26-OSia5DgnCEKQkDjnbBDw2RX7Oo
tlsproxy: 2017/09/28 16:32:00 Getting cert for status.myownconference.ru
tlsproxy: 2017/09/28 16:32:00 GetCertificate debug: acme/autocert: missing certificate
```

I found this error multiple times in the logs:
```
tlsproxy: 2017/09/27 21:13:24 GetCertificate debug: 400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce avvhLzLc5ahbGct1-2S1pKYBcPAn5rqu3iISVUYPPDk
tlsproxy: 2017/09/28 06:57:34 GetCertificate debug: 400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce yf_r4K4gCO82NHz9nT_tdEM9KD27oY7VkXm4ivxgIIs
tlsproxy: 2017/09/28 08:44:35 GetCertificate debug: 400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce 3SBW7IuGvNAq8MeE0gGLVl4zJelWC9Ca20It7mWq9iY
tlsproxy: 2017/09/28 16:31:59 GetCertificate debug: 400 urn:acme:error:badNonce: JWS has invalid anti-replay nonce zvBhhB5kyR2Mxr26-OSia5DgnCEKQkDjnbBDw2RX7Oo
```

I restarted the server and now I get:
```
tlsproxy: 2017/09/28 22:27:55 GetCertificate debug: acme: identifier authorization failed
tlsproxy: 2017/09/28 22:29:08 GetCertificate debug: acme: identifier authorization failed
```
The previous one now works fine after a restart as planned: https://status.yourtaximeter.com/

**Comment by chrisDeFouRire** [comment]
It looks like this one is a different kind of error... It may be a race condition in Let's Encrypt (https://github.com/certbot/certbot/issues/2244). Although they say the solution is to retry, TLSproxy is using a standard go library for LE certs, so I can't really do anything...

Also, it looks like these problems are really hard to debug, borderline Heisenbugs... and obviously I can't reproduce them on my computer because your DNS doesn't point to it.

I'm sorry to say I don't know how I can help...

**Comment by jarthod** [comment]
Ok I see, it's https://github.com/golang/crypto/blob/master/acme/autocert/autocert.go right?
I could take the issue to them but it looks like they're avoiding it ^^ no public issues on github, no link to report bugs in the doc..

**Comment by chrisDeFouRire** [comment]
Yes, it's the package I'm using (I'm using go 1.9 to build the github release, fairly up to date).

It's maintained (there are recent commits) so we can only hope it will get better... If only we could pinpoint what's wrong, but I obviously can't debug an issue I can't reproduce.

**Comment by jarthod** [comment]
We can hope ;)

**Comment by chrisDeFouRire** [comment]
... I meant I can't invest the time and efforts to solve this problem if it's a bug in go's libs. There's a number of caches, from what I've seen in the code, in addition to the cert cache. The problem may lie there, since a restart seems to solve the problem. Caching is hard ;)
Are you using a single host for tlsproxy? or multiple hosts?

**Comment by jarthod** [comment]
Yes caching is hard ;) it's definitely in some kind of intermediary (memory) cache as there's no file created for these hosts. I'm running it on a single node, yes. I guess I can always setup a cron to restart the server periodically ^^

**Comment by chrisDeFouRire** [comment]
I've released two updates recently... One fixes tlsproxy by using Letsencrypt's ALPN challenge (because SNI challenge isn't supported anymore), the other fixes HTTP proxy because it was broken except for the corner case I used to test 🤣

I'm closing this issue, please tell me if these new versions fix your problems...

**Comment by jarthod** [comment]
Hi @chrisDeFouRire, I've actually switched to https://github.com/GUI/lua-resty-auto-ssl a while back as I needed something more reliable, but thanks for the update!
